### ISSUE TITLE
Error: Problem connect to Firehose. Please ensure Internet connection is working.

### ISSUE THREAD

**Issue by MaralMgh** [andreamrau/EDGE-in-TCGA#1]
Hello, I am not sure if you are still supporting this repository. I have the below problem

rnaseq.ov <- getTCGA(disease="OV", data.type="RNASeq", type="RPKM")
Error: Problem connect to Firehose. Please ensure Internet connection is working.

How should I deal with this?

**Comment by andreamrau** [comment]
Thanks for your question -- there indeed hasn't been much active maintenance on this repo in recent years, and unfortunately I see that the package we used at the time to download the TCGA data (TCGA2STAT) has been archived on CRAN since 2020 (https://cran.r-project.org/web/packages/TCGA2STAT/index.html). Since that package is no longer maintained, that may explain in part the error you're getting. 

In any case, I think it would probably now be a better idea to use one of the more recent availale Bioconductor packages to download the TCGA data (e.g., [cBioPortalData](https://bioconductor.org/packages/release/bioc/html/cBioPortalData.html), [TCGAbiolinks](https://bioconductor.org/packages/release/bioc/html/TCGAbiolinks.html), or [curatedTCGAdata](https://bioconductor.org/packages/release/data/experiment/html/curatedTCGAData.html)), from there it should be relatively straightforward to format the data as needed for the rest of the code in this repo or for other analyses.
